/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Daniel' at '05.05.17 15:33' with Gradle 2.14.1
 *
 * @author Daniel, @date 05.05.17 15:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
