import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SpeechToText extends AudioProcessing {
	public static void main(String... args) throws Exception {

		FileChooser myChooser = new FileChooser();

		// Ort der ffmpegEXE und der beiden Audio Channels
		String fmmpegExeOrdner = myChooser.choose().getParent();

		
// ----------------------------------------------------------------

//		 manageJavaInput MyManage = new manageJavaInput();
//		 MyManage.manage(fmmpegExeOrdner);

// ----------------------------------------------------------------

		SpeakerSeperation spsep = new SpeakerSeperation();
		spsep.processFiles(fmmpegExeOrdner);
		bundler.generiereJSON();

	}
}
