import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SpeechToText extends AudioProcessing {
	public static void main(String... args) throws Exception {

		manageJavaInput MyManage = new manageJavaInput();
		MyManage.manage();
		
		
//		ffmpegClass myffmpegClass = new ffmpegClass();
//		myffmpegClass.audioToMetaData();

		// -----------------------------------------------------------------------------------

//		File caStarttimes = new File("C:\\Users\\d_tham01\\Desktop\\C1.txt");
//		File kunStarttimes = new File("C:\\Users\\d_tham01\\Desktop\\K1.txt");
//		File caEndttimes = new File("C:\\Users\\d_tham01\\Desktop\\C2.txt");
//		File kunEndttimes = new File("C:\\Users\\d_tham01\\Desktop\\K2.txt");
//
//		TimesCut myTimesCut = new TimesCut();
//
//		myTimesCut.identifyStartTimes(caStarttimes);
//		myTimesCut.identifyEndTimes(caEndttimes);
//		myTimesCut.identifyStartTimes(kunStarttimes);
//		myTimesCut.identifyEndTimes(kunEndttimes);
		// ----------------------------------------------------------------------------------
//
//		SpeakerSeperation spsep = new SpeakerSeperation();
//		spsep.processFiles();

		
//		 FileChooser myC = new FileChooser();
//		 test2 mytest2 = new test2();
//		 SpeakerSeperation SS = new SpeakerSeperation();
//		 
//		 File startzeitenTXT = myC.choose();
//		 File endzeitenTXT = myC.choose();
//		 double[] startzeiten = SS.TextToTime(startzeitenTXT);
//		 double[] endzeiten = SS.TextToTime(endzeitenTXT);
//		
//		 mytest2.cutAudio(startzeiten, endzeiten);
		 
		// AudioProcessing audio= new AudioProcessing();
		// audio.processAudio();
		// AsyncProcess process= new AsyncProcess();
		// process.asyncRecognizeGcs("gs://audio_projektseminar/TestDateien/channel1.wav");

	}
}
